[build]
  # Ruta del directorio donde Netlify encontrará los archivos para construir el proyecto
  publish = "dist"
  # Comando de construcción para crear el contenido del sitio
  command = "npm run build"
  # Versión de Node.js (opcional pero recomendado, si tienes problemas de compatibilidad)
  node_version = "18.17.1"

[dev]
  # Configuración para el entorno de desarrollo local en Netlify
  framework = "vite" # Asegura que se use el servidor de desarrollo de Vite
  targetPort = 5173 # El puerto predeterminado de Vite para desarrollo local
  port = 8888 # Puerto en el que Netlify servirá la aplicación localmente

[[plugins]]
  # Agrega plugins de Netlify, si es necesario
  package = "@netlify/plugin-functions-install-core"
