[build]
  publish = "dist"
  command = "npm run build"
  node_version = "18.17.1"


[dev]
  # Configuración para el entorno de desarrollo local en Netlify
  framework = "vite" # Asegura que se use el servidor de desarrollo de Vite
  targetPort = 5173 # El puerto predeterminado de Vite para desarrollo local
  port = 8888 # Puerto en el que Netlify servirá la aplicación localmente

[[plugins]]
  # Agrega plugins de Netlify, si es necesario
  package = "@netlify/plugin-functions-install-core"
